#baseURL = "https://ole12138.github.io/"
languageCode = "zh-cn"
title = "Jingmin's blog"
theme = "bootie-docs"
#copyright = "test© 2020"
copyright = "Copyright (c) 2020, Jingmin; All rights reserved."

# Your Google analytics code.
#googleAnalytics = "UA-98254666-1"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Rss format
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"
rssLimit = 20

[params]
  description    = "喜欢，并为此欢喜"
  withSitePosts  = true
  #searchDomain   = "https://ole12138.github.io"
  noCategoryLink = true
  repositoryUrl  = "https://github.com/ole12138/ole12138.github.io"
  highlightStyle = "github"
  math = false

[markup]
  defaultMarkdownHandler = "goldmark"
  #defaultMarkdownHandler = "pandoc"
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
  
# Main menu which appears below site header.
#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Series"
url = "/series"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 999


# Enable tags.
[taxonomies]
   tag = "tags"
   series = "series"
   category = "categories"