name: github pages

on:
  push:
    branches:
    # 你的hugo源码分支
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup pandoc
      #uses: maxheld83/pandoc@v2
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.9.2' # The pandoc version to download (if necessary) and use

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build for Gitee
      run: hugo --config gitee-config.toml,config.toml --minify
    
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        # 注意替换为你的 GitHub 源仓库地址
        source-repo: git@github.com:ole12138/ole12138.github.io.git
        # 注意替换为你的 Gitee 目标仓库地址
        destination-repo: git@gitee.com:ole12138/ole12138.git

    - name: Build for Github
      run: hugo --config github-config.toml,config.toml --minify
    
    - name: Deploy to Github
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        publish_branch: master 
