name: github pages

on:
  push:
    branches:
    # 你的hugo源码分支
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup pandoc
      #uses: maxheld83/pandoc@v2
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.9.2' # The pandoc version to download (if necessary) and use

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        publish_branch: master 
